#!/bin/bash

user=""

if [[ $(whoami) != "root" ]];then
        echo "Must run as root"
        exit 1
fi
echo "deleting files"
rm -r /etc/udev/rules.d/80-insert-yubi.rules /usr/local/bin/trigger /usr/local/bin/keyring-unlock /home/$user/.pass /home/$user/.keyring-unlocker.log
echo "restarting service and udev rules"
systemctl restart pcscd
killall gpg-agent
udevadm control --reload
echo "bye"
