#!/bin/bash

user=jay

if [[ $(whoami) != "root" ]];then
        echo "Must run as root"
        exit 1
fi

echo "deleting files"
rm -r /etc/udev/rules.d/80-insert-yubi.rules /usr/local/bin/trigger /usr/local/bin/keyring-unlock /home/$user/.pass /home/$user/.keyring-unlocker.log $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
echo "restarting service and udev rules"
udevadm control --reload
echo "bye"
