#!/bin/bash

if [[ $(whoami) != "root" ]];then
        echo "Must run as root"
        exit 1
fi

echo "Starting init..."

while true ;do
	read -p "user: " username
	if [[ $username == "" ]];then
		echo "Enter a username"
	elif [[ $username != "" ]];then
		if id $username>>/dev/null ;then
			id=$(id $username -u)
			echo "Configuring for $username with uid=$id"
			break 3
		fi
	fi
done

sed -i "s/user=.*/user="$username"/g" trigger
sed -i "s/userid=.*/userid="$id"/g" trigger

chmod +x trigger
chmod +x keyring-unlock

mv trigger /usr/local/bin/
mv keyring-unlock /usr/local/bin/

touch /home/$username/.keyring-unlocker.log
chmod +rw /home/$username/.keyring-unlocker.log

echo "Inserting udev rule"
	mv 80-insert-yubi.rules /etc/udev/rules.d/
	udevadm control --reload

### test if secret file decrypts and if the password is correct
echo "Final test"

echo "take yubikey out and insert it back in"
I=0
while (( I < 13 )); do
	echo $I
	sleep 1
        (( I++ ))
        if tail -2 /home/$username/.keyring-unlocker.log | grep "Device-Added" ;then
                udevWorking="yes"
                echo "Success yubi is detected by udev"
                if tail -3 /home/$username/.keyring-unlocker.log | grep "Detected-Decrypting" ;then
			echo "trying to unlock..."
			sleep 2
			if tail -3 /home/$username/.keyring-unlocker.log | grep "Keyring-Unlocked" ;then
				echo "keyring should be unlocked now"
			else
				echo "Failed to unlock the keyring"
                        fi
                               	break 3
                fi
        fi
done

if (( I >13 ));then
		if [[ udevWorking == "yes" ]];then
				echo "udev rule is working but gpg is not detecting"
		else
				echo "udev and gpg are not detecting the yubikey"
		fi
fi

sed -i "s/user=.*/user="$username"/g" remove-unlocker
chmod +x remove-unlocker
echo "if you want to memove the unlocker execute the remove-unlocker script"
